### ISSUE TITLE
external-tools config lists do not get replaced

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#149]
Changing the argument list of an external tool inside your `decker.yaml` does not change the argument list of the executed program unless you wrap it inside the os-namespace of the system you are running on:

```
external-tools:
    whisper:
        command: "foobar"
        arguments:
            - "bar"
            -  "foo"
```

Does not change the executed command to "foobar bar foo". If I configure this on a linux machine though:

```
external-tools:
    whisper:
        linux:
            command: "foobar"
            arguments:
                - "bar"
                -  "foo"
```

It does have an effect.

The `default.yaml` does not seem to have an os entry to take priority so it simply seems like the arguments do not get replaced if placed in a `decker.yaml`.
