### ISSUE TITLE
Cleaning up title-page templates

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#42]
Writing documentation for all the title-page options made clear that right now the default template and other templates diverge a lot and each needs custom documentation if one wants to explain how and what values are configurable.

I propose the following variables to be used in all title-pages with resource packs only adding features as to keep documentation minimal:

```
---
title: 'Slide or page Title'
subtitle: 'Slide or page Subtitle'
author: 'Singular Author of the slides, presented centered'
affilitation: 'Affiliation / Institute of the singular author'
copyright: 'Copyright for the slide or page'
author-link: 'Link to the singular author\'s website'
affiliation-link: 'Link to the singular author\'s affiliation\'s website'
copyright-link: 'Link to the documentation of the used copyright (e.g. creative commons)'

authors:
    - name: 'Name of one of multiple authors'
      affiliation: 'Affiliation of one of multiple authors'
      name-link: 'Link to one of multiple authors\' website'
      affiliation-link: 'Link to one of multiple authors\' affiliation\'s website.'
    - name: 'Name of one of multiple authors'
      affiliation: 'Affiliation of one of multiple authors'
      name-link: 'Link to one of multiple authors\' website'
      affiliation-link: 'Link to one of multiple authors\' affiliation\'s website.'

date: 'Date of release'

teaser: 'Path to an image presented as a teaser image for the whole presentation'

logos:
    - 'Path to an image to be used as a logo'
    - 'Path to a different image file'
---
```

These include only variables related to the title-page.

Additional issues will be created for other template variables.

Examples for how these turn out can be found in the `template-improvements` branch.

Additional input is appreciated.

**Comment by marcerich** [comment]
We had a longer discussion about similar topics in the past. It's always not easy where to draw the demarcation line imho. Anyways, I agree, more potential information for the title page would/could be nice. I see this more as meta data of the presentation which might also end up on the title page or even on other slides. 

In general, we should cluster the information as soon as it has `>1` associated entries. E.g., I would cluster the logos with the affiliation(s) etc. Next questions arises if one want also the group/department etc. However, some meta is inherited by reveal/pandoc and it is always a question how to handle this (e.g., keeping backwards compatibility or not). Some more thought:

1. Often one also wants to add the venue (think keynotes, conference talks, etc.).   
2. Also, a closing page with the same layout and (maybe floating blocks in the foreground with "thank you for listening" and/or "questions? makes sense.
3. Instead of `link` we should name meta more precisely, i.e., `url`
4. How about `banners` often used .

Could look like this:


```
---
title: 'Slide or page Title'
subtitle: 'Slide or page Subtitle'
author: 'Singular Author of the slides, presented centered'
author-url: 'URL to the singular author\'s website'

affiliation: 
   institution: 'Affiliation / Institute of the singular author'
   logo: 'Path to an image to be used as a logo'
   url: 'URL to the singular author\'s affiliation\'s website'

copyright: 
   type: 'Copyright for the slide or page'
   url: 'Link to the documentation of the used copyright (e.g. creative commons)'

authors:
   author: 
      name: 'Name of one of multiple authors'
      url: 'URL to this author\'s affiliation\'s website'
      affiliation: 
         institution: 'Affiliation / Institute of this author'
         logo: 'Path to an image to be used as a logo'
         url: 'URL to this author\'s affiliation\'s website'
   author: 
      name: 'Name of one of multiple authors'
      url: 'URL to this author\'s affiliation\'s website'
      affiliation: 
         institution: 'Affiliation / Institute of this author'
         logo: 'Path to an image to be used as a logo'
         url: 'URL to this author\'s affiliation\'s website'

date: 'Date of release'

teaser: 'Path to an image presented as a teaser image for the whole presentation'
banner: 'Path to an image presented as a banner image for the title/closing page  presentation' 

---
```

rfc
