### ISSUE TITLE
Path resolution from default.yaml for meta variables is incorrect

### ISSUE THREAD

**Issue by monofon** [decker-edu/decker#8]
```yaml:
template:
  deck:
    css:
      - bla.css
```

is not resolved to the correct path.
